name: arenaz_mobile_v2
description: "Play everyhwere."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter_modular: ^6.3.4
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  mobx: ^2.5.0
  mobx_codegen: ^2.7.0
  flutter_mobx: ^2.3.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.3"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/arenaz_logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/arenaz_logo.png"
    background_color: "#ffffff"
    theme_color: "#2196f3"
  windows:
    generate: true
    image_path: "assets/images/arenaz_logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/arenaz_logo.png"


flutter:
  fonts:
    - family: ChakraPetch
      fonts:
        - asset: assets/fonts/ChakraPetch-Light.ttf
          weight: 300
        - asset: assets/fonts/ChakraPetch-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/ChakraPetch-Regular.ttf
          weight: 400
        - asset: assets/fonts/ChakraPetch-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/ChakraPetch-Medium.ttf
          weight: 500
        - asset: assets/fonts/ChakraPetch-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/ChakraPetch-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ChakraPetch-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/ChakraPetch-Bold.ttf
          weight: 700
        - asset: assets/fonts/ChakraPetch-BoldItalic.ttf
          weight: 700
          style: italic
  uses-material-design: true

  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
